baseURL = 'https://arcolaus.github.io'
languageCode = 'en-us'
title = 'Laniidae'
theme = "hugo-theme-stack"

[params]
mainSections = ["post"]
featuredImageField = "image"
favicon = "/favicon.png"
rssFullContent = true

[params.footer]
since = 2_020

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
subtitle = "The Birds Don't Sing, They Screech in Pain"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/oasis-square.jpg"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"


[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 3

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true


[menu]
main = []

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Arcolaus"

[menu.social.params]
icon = "brand-github"


[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
